<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.8.4 setup script
 * Date: Wed, 02 Jan 2019 16:38:34 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: 186.67.71.235 [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = '186.67.71.235';
$cfg['Servers'][$i]['host'] = '186.67.71.235';
$cfg['Servers'][$i]['port'] = 3306;
$cfg['Servers'][$i]['socket'] = '3306';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'vigomaq';
$cfg['Servers'][$i]['password'] = 'rtwvhhTE8X75bGyH';

/* End of servers configuration */

$cfg['blowfish_secret'] = '0Of$21w`w>lbDT[RV86)xz%w.]tV.uE,';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>