CREATE DATABASE LINK DBL_HABITABILIDAD
    CONNECT TO CONSUL_HABITABILIDAD IDENTIFIED BY pet4gs5RWZf
    USING '(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=192.168.31.160)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=oradesa)))';